# Generated by Django 5.2.4 on 2025-07-24 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('board_type', models.CharField(choices=[('general', '일반게시판'), ('gallery', '갤러리'), ('admin', '관리자게시판')], default='general', max_length=20, verbose_name='게시판 구분')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='좋아요')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='이미지')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'ordering': ['-created_at'],
            },
        ),
    ]
